/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hJmX5TKL5zM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import Link from "next/link"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { ResponsiveBar } from "@nivo/bar"
import { ResponsiveLine } from "@nivo/line"
import { ResponsivePie } from "@nivo/pie"

export default function Analytics() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center bg-background border-b">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <div className="flex items-center gap-4">
            <MountainIcon className="h-6 w-6" />
            <h1 className="text-2xl font-bold text-muted">Cyber Proof</h1>
          </div>
          <span className="sr-only">Illicit Drug Trafficking Analytics</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            href="/dashboard"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}>
            Dashboard
          </Link>
          <Link
            href="/investigations"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}>
            Investigations
          </Link>
          <Link
            href="/analytics"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}>
            Analytics
          </Link>
          <Link
            href="/settings"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}>
            Settings
          </Link>
        </nav>
      </header>
      <div className="mx-auto max-w-4xl space-y-8 py-8">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold">Illicit Drug Trafficking Analytics</h1>
          <p className="text-muted-foreground">
            Identify users behind Telegram, WhatsApp and Instagram drug trafficking activities.
          </p>
        </div>
        <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
          <Card>
            <CardHeader>
              <CardTitle>Telegram</CardTitle>
              <CardDescription>Analyze Telegram drug trafficking activities</CardDescription>
            </CardHeader>
            <CardContent>
              <BarChart className="aspect-[4/3]" />
            </CardContent>
            <CardFooter>
              <Button variant="outline" size="sm">
                View Details
              </Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>WhatsApp</CardTitle>
              <CardDescription>Analyze WhatsApp drug trafficking activities</CardDescription>
            </CardHeader>
            <CardContent>
              <LineChart className="aspect-[4/3]" />
            </CardContent>
            <CardFooter>
              <Button variant="outline" size="sm">
                View Details
              </Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Instagram</CardTitle>
              <CardDescription>Analyze Instagram drug trafficking activities</CardDescription>
            </CardHeader>
            <CardContent>
              <PieChart className="aspect-[4/3]" />
            </CardContent>
            <CardFooter>
              <Button variant="outline" size="sm">
                View Details
              </Button>
            </CardFooter>
          </Card>
        </div>
        <div className="space-y-2 text-center">
          <h2 className="text-2xl font-bold">Suspicious Activity Alerts</h2>
          <p className="text-muted-foreground">Get real-time alerts on suspicious drug trafficking activities.</p>
        </div>
        <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle>Telegram Alerts</CardTitle>
              <CardDescription>Receive alerts on suspicious Telegram activities</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="font-medium">User ABC123</div>
                  <Badge variant="outline">High Risk</Badge>
                </div>
                <div className="text-muted-foreground">
                  Suspicious drug trafficking activities detected in Telegram group "Narcotics Exchange".
                </div>
                <div className="flex items-center justify-between">
                  <div className="font-medium">User XYZ456</div>
                  <Badge variant="outline">Medium Risk</Badge>
                </div>
                <div className="text-muted-foreground">
                  Potential drug-related content shared in Telegram channel "Illicit Goods".
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button variant="outline" size="sm">
                View All Alerts
              </Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>WhatsApp Alerts</CardTitle>
              <CardDescription>Receive alerts on suspicious WhatsApp activities</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="font-medium">User 123ABC</div>
                  <Badge variant="outline">High Risk</Badge>
                </div>
                <div className="text-muted-foreground">
                  Suspicious drug-related keywords detected in WhatsApp group "Narcotics Network".
                </div>
                <div className="flex items-center justify-between">
                  <div className="font-medium">User 456XYZ</div>
                  <Badge variant="outline">Medium Risk</Badge>
                </div>
                <div className="text-muted-foreground">
                  Potential drug trafficking activities identified in WhatsApp chat "Illicit Goods Exchange".
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button variant="outline" size="sm">
                View All Alerts
              </Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Instagram Alerts</CardTitle>
              <CardDescription>Receive alerts on suspicious Instagram activities</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="font-medium">User_ABC123</div>
                  <Badge variant="outline">High Risk</Badge>
                </div>
                <div className="text-muted-foreground">
                  Suspicious drug-related content detected on Instagram account "narcotics_exchange".
                </div>
                <div className="flex items-center justify-between">
                  <div className="font-medium">User_XYZ456</div>
                  <Badge variant="outline">Medium Risk</Badge>
                </div>
                <div className="text-muted-foreground">
                  Potential drug trafficking activities identified on Instagram profile "illicit_goods_hub".
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button variant="outline" size="sm">
                View All Alerts
              </Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </div>)
  );
}

function BarChart(props) {
  return (
    (<div {...props}>
      <ResponsiveBar
        data={[
          { name: "Jan", count: 111 },
          { name: "Feb", count: 157 },
          { name: "Mar", count: 129 },
          { name: "Apr", count: 150 },
          { name: "May", count: 119 },
          { name: "Jun", count: 72 },
        ]}
        keys={["count"]}
        indexBy="name"
        margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
        padding={0.3}
        colors={["#2563eb"]}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 4,
          tickPadding: 16,
        }}
        gridYValues={4}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        tooltipLabel={({ id }) => `${id}`}
        enableLabel={false}
        role="application"
        ariaLabel="A bar chart showing data" />
    </div>)
  );
}


function LineChart(props) {
  return (
    (<div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application" />
    </div>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}


function PieChart(props) {
  return (
    (<div {...props}>
      <ResponsivePie
        data={[
          { id: "Jan", value: 111 },
          { id: "Feb", value: 157 },
          { id: "Mar", value: 129 },
          { id: "Apr", value: 150 },
          { id: "May", value: 119 },
          { id: "Jun", value: 72 },
        ]}
        sortByValue
        margin={{ top: 10, right: 10, bottom: 10, left: 10 }}
        cornerRadius={0}
        padAngle={0}
        borderWidth={1}
        borderColor={"#ffffff"}
        enableArcLinkLabels={false}
        arcLabel={(d) => `${d.id}`}
        arcLabelsTextColor={"#ffffff"}
        arcLabelsRadiusOffset={0.65}
        colors={["#2563eb"]}
        theme={{
          labels: {
            text: {
              fontSize: "18px",
            },
          },
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
        }}
        role="application" />
    </div>)
  );
}
