/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/u5qVyCdlMn7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { Switch } from "@/components/ui/switch"

export default function Component() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header
        className="px-4 lg:px-6 h-14 flex items-center justify-between bg-background border-b">
        <Link href="/dashboard" className="flex items-center justify-center" prefetch={false}>
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Drug Trafficking Monitoring Dashboard</span>
        </Link>
        <nav className="flex gap-4 sm:gap-6">
          <Link
            href="/dashboard"
            className="text-sm font-medium hover:underline underline-offset-4 text-foreground"
            prefetch={false}>
            Dashboard
          </Link>
          <Link
            href="/investigations"
            className="text-sm font-medium hover:underline underline-offset-4 text-foreground"
            prefetch={false}>
            Investigations
          </Link>
          <Link
            href="/analytics"
            className="text-sm font-medium hover:underline underline-offset-4 text-foreground"
            prefetch={false}>
            Analytics
          </Link>
          <Link
            href="/settings"
            className="text-sm font-medium hover:underline underline-offset-4 text-foreground font-bold"
            prefetch={false}>
            Settings
          </Link>
        </nav>
      </header>
      <main className="flex-1 overflow-y-auto">
        <section className="py-12 md:py-16 lg:py-20">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <div className="space-y-6 md:space-y-8 lg:space-y-10">
              <div className="text-center">
                <h1 className="text-3xl font-bold md:text-4xl lg:text-5xl">Settings</h1>
                <p className="mt-3 text-muted-foreground md:text-lg lg:text-xl">
                  Manage your dashboard settings and preferences.
                </p>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <Card>
                  <CardHeader>
                    <CardTitle>General</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-4">
                      <div>
                        <Label htmlFor="dashboard-name">Dashboard Name</Label>
                        <Input
                          id="dashboard-name"
                          type="text"
                          defaultValue="Drug Trafficking Monitoring Dashboard" />
                      </div>
                      <div>
                        <Label htmlFor="timezone">Timezone</Label>
                        <Select id="timezone" defaultValue="America/Los_Angeles">
                          <SelectTrigger>
                            <SelectValue placeholder="Select timezone" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="America/Los_Angeles">Pacific Time (US & Canada)</SelectItem>
                            <SelectItem value="America/New_York">Eastern Time (US & Canada)</SelectItem>
                            <SelectItem value="Europe/London">London</SelectItem>
                            <SelectItem value="Asia/Tokyo">Tokyo</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                      <div>
                        <Label htmlFor="language">Language</Label>
                        <Select id="language" defaultValue="en">
                          <SelectTrigger>
                            <SelectValue placeholder="Select language" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="en">English</SelectItem>
                            <SelectItem value="es">Español</SelectItem>
                            <SelectItem value="fr">Français</SelectItem>
                            <SelectItem value="de">Deutsch</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                    </div>
                  </CardContent>
                  <CardFooter>
                    <Button>Save Changes</Button>
                  </CardFooter>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Notifications</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-4">
                      <div>
                        <Label htmlFor="notification-email">Email Notifications</Label>
                        <Input id="notification-email" type="email" defaultValue="user@example.com" />
                      </div>
                      <div className="flex items-center gap-2">
                        <Switch id="notification-desktop" />
                        <Label htmlFor="notification-desktop">Desktop Notifications</Label>
                      </div>
                      <div className="flex items-center gap-2">
                        <Switch id="notification-mobile" />
                        <Label htmlFor="notification-mobile">Mobile Notifications</Label>
                      </div>
                    </div>
                  </CardContent>
                  <CardFooter>
                    <Button>Save Changes</Button>
                  </CardFooter>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Security</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-4">
                      <div>
                        <Label htmlFor="password">Change Password</Label>
                        <Input id="password" type="password" placeholder="Enter new password" />
                      </div>
                      <div className="flex items-center gap-2">
                        <Switch id="two-factor" />
                        <Label htmlFor="two-factor">Enable Two-Factor Authentication</Label>
                      </div>
                    </div>
                  </CardContent>
                  <CardFooter>
                    <Button>Save Changes</Button>
                  </CardFooter>
                </Card>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>)
  );
}

function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
